version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: astronomy
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - "./week3data:/data/week3data"