create table person (id bigint generated by default as identity, name varchar(255), primary key (id));
create table person_grades (person_id bigint not null, subject_id bigint, assessment float);
create table subject (id bigint generated by default as identity, name varchar(255), primary key (id));
alter table person_grades add constraint FKlydl381r5ph04s49giw2usoj7 foreign key (subject_id) references subject;
alter table person_grades add constraint FK6wr8di96v9kxrkmeo9qw52q22 foreign key (person_id) references person;
