version: 0.2

env:
  variables:
    build_version: "0.1"

phases:
  install:
    commands:
      # install prerequisites
      - export ANT_HOME=$(find $MFPRODBASE/remotedev/ant -type d -name 'apache-ant*')
      - export PATH=$JAVA_HOME/bin:$ANT_HOME/bin:$PATH
      - . $MFPRODBASE/bin/cobsetenv
    finally:
      # nothing special here 
  pre_build:
    commands:
  build:
    commands:
      # build
      - ant -lib $COBDIR/lib/mfant.jar -f LoanAmortTests/build.xml
      # prepare for tests
      - mfjarprogmap -directory LoanAmortTests/bin
      - jar -cvf LoanAmortTests/bin/LoanAmortTests.jar -C LoanAmortTests/bin .
      # get compiled sources from secondary input artifacts
      - export CLASSPATH=$CLASSPATH:$CODEBUILD_SRC_DIR_BuildArtifact/lib/loanamort-1.0.0.jar
      # run tests; go to the bin folder due to mfunit restriction on saving the report.txt file in -outdir
      - cd LoanAmortTests/bin
      - cobmfurunj -show-progress -report:junit -outdir:reports LoanAmortTests.jar
      - cd ../..
      - cat LoanAmortTests/bin/reports/LoanAmortTests-report.txt
      # create html reports folder
      - ant -lib $COBDIR/lib/mfant.jar -f LoanAmortTests/mfunitreport.xml
      # done
  post_build:
    commands:
artifacts:
  files:
    - reports/**/*
    - html_reports/**/*
  base-directory: LoanAmortTests/bin
  name: mfunit-$(AWS_REGION)-$(date +%Y-%m-%d) 